version: 2

attach: &attach
  attach_workspace:
    at: /home/circleci

register_nypr_publisher_lib: &register_nypr_publisher_lib
  run:
    name: make global symlink
    command: cd /home/circleci/nypr-publisher-lib && yarn link

restore_node: &restore_node
  restore_cache:
    key: node-deps-{{ arch }}-{{ checksum "yarn.lock" }}

install_node: &install_node
  run:
    name: node deps
    command: |
      if [ ! -d node_modules ]; then
        yarn --pure-lockfile
      fi

save_node: &save_node
  save_cache:
    key: node-deps-{{ arch }}-{{ checksum "yarn.lock" }}
    paths:
      - node_modules

restore_bower: &restore_bower
  restore_cache:
    key: bower-deps-{{ arch }}-{{ checksum "bower.json" }}

install_bower: &install_bower
  run:
    name: bower deps
    command: |
      if [ ! -d bower_components ]; then
        npx bower i
      fi

save_bower: &save_bower
  save_cache:
    key: bower-deps-{{ arch }}-{{ checksum "bower.json" }}
    paths:
      - bower_components

build_modernizr: &build_modernizr
  run:
    name: Build modernizr
    command: npx grunt modernizr:dist

run_client_tests: &run_client_tests
  run:
    name: link and test
    command: |
      yarn link nypr-publisher-lib
      npx ember test

container_defaults: &defaults
  docker:
    - image: circleci/node:8.7-browsers
      environment:
        JOBS: 2

jobs:
  install:
    <<: *defaults
    working_directory: /home/circleci/nypr-publisher-lib

    steps:
      - checkout

      - <<: *restore_node
      - <<: *install_node
      - <<: *save_node

      - <<: *restore_bower
      - <<: *install_bower
      - <<: *save_bower

      - persist_to_workspace:
          root: /home/circleci
          paths:
            - nypr-publisher-lib

  test:
    <<: *defaults
    working_directory: /home/circleci/nypr-publisher-lib
    environment:
      CIRCLE_TEST_REPORTS: test-results

    steps:
      - checkout
      - <<: *restore_node
      - <<: *restore_bower

      - run:
          name: Run addon tests
          command: |
            sudo yarn global add greenkeeper-lockfile@1
            greenkeeper-lockfile-update
            npx ember test
            greenkeeper-lockfile-upload

      - store_test_results:
          path: test-results/

  deploy:
    <<: *defaults
    working_directory: /home/circleci/nypr-publisher-lib
    steps:
      - <<: *attach
      - run:
          name: Deploy to GitHub Pages
          command: |
            git config --global user.email "deploy@circleci"
            git config --global user.name "deploy"
            npx ember deploy production

workflows:
  version: 2
  just-test:
    jobs:
      - install
      - test:
          requires:
            - install
  test-and-deploy:
    jobs:
      - install:
          filters:
            branches:
              only: master
      - test:
          requires:
            - install
      - setup_test_clients:
          requires:
            - install
      - test_wnyc:
          requires:
            - setup_test_clients
      - test_wqxr:
          requires:
            - setup_test_clients
      - test_wnyc_studios_ember:
          requires:
            - setup_test_clients
      - test_wnyc_studios_cypress:
          requires:
            - setup_test_clients
      - test_new_sounds:
          requires:
            - setup_test_clients
      - deploy:
          requires:
            - test
            - test_wnyc
            - test_wqxr
            - test_wnyc_studios_ember
            - test_wnyc_studios_cypress
            - test_new_sounds
